- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - "trigger-build":
            vars:
              webhook_url: "***REMOVED***/oapi/v1/namespaces/thoth-test-core/buildconfigs/osiris-observer/webhooks"
    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
