apiVersion: v1
kind: Template
metadata:
  name: osiris-observer-imagestream
  annotations:
    description: >
      This is Osiris Observer ImageStream Template.
    openshift.io/display-name: 'Thoth: Osiris Observer - ImageStream'
    tags: ai-stacks,aistacks,build,build-aggregator,build-analysis,thoth,osiris,osiris-observer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris Observer ImageStream Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-observer-imagestream
    app: osiris
    component: osiris-observer

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: osiris
        component: osiris-observer
      name: osiris-observer
    spec:
      name: ${IMAGE_STREAM_TAG}

parameters:
  - description: Tag of the ImageStream to use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG

value: 'latest'
